// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpdio2wFCV7RzMDHQx_fL-Z1nd7QtKqzQ',
    appId: '1:1066305707801:web:db097e844837e5e9872f88',
    messagingSenderId: '1066305707801',
    projectId: 'thoriq-pbm',
    authDomain: 'thoriq-pbm.firebaseapp.com',
    storageBucket: 'thoriq-pbm.firebasestorage.app',
    measurementId: 'G-7RELDRYT1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPDDbV_-P0UZwAHAe8odyze0XvWJ17TcQ',
    appId: '1:1066305707801:android:03661fe38cddc53c872f88',
    messagingSenderId: '1066305707801',
    projectId: 'thoriq-pbm',
    storageBucket: 'thoriq-pbm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBym9UGa4IfW-vJp-DPJXMgtQBSYsZZn1s',
    appId: '1:1066305707801:ios:06df0baac3fd278c872f88',
    messagingSenderId: '1066305707801',
    projectId: 'thoriq-pbm',
    storageBucket: 'thoriq-pbm.firebasestorage.app',
    iosBundleId: 'com.example.flutterFilm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBym9UGa4IfW-vJp-DPJXMgtQBSYsZZn1s',
    appId: '1:1066305707801:ios:06df0baac3fd278c872f88',
    messagingSenderId: '1066305707801',
    projectId: 'thoriq-pbm',
    storageBucket: 'thoriq-pbm.firebasestorage.app',
    iosBundleId: 'com.example.flutterFilm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpdio2wFCV7RzMDHQx_fL-Z1nd7QtKqzQ',
    appId: '1:1066305707801:web:e2d39adc45e4f05a872f88',
    messagingSenderId: '1066305707801',
    projectId: 'thoriq-pbm',
    authDomain: 'thoriq-pbm.firebaseapp.com',
    storageBucket: 'thoriq-pbm.firebasestorage.app',
    measurementId: 'G-W5NW4J8SX0',
  );
}
